[package]
name = "config-dns-daemon"
version = "0.1.0"
authors = ["Martin Sehnoutka <msehnout@redhat.com>"]

[dependencies]
docopt = "1"
env_logger = "0.5.10"
failure = "0.1.1"
log = "0.4.0"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"