[package]
name = "dnsconfigd"
version = "0.1.0"
authors = ["Martin Sehnoutka <msehnout@redhat.com>"]

[dependencies]
dbus = "0.6"
docopt = "1"
env_logger = "0.5"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
